School/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace School.Controllers
{
    public class AdminController : Controller
    {
        SchoolDBEntities scl = null;
        public AdminController()
        {
            scl = new SchoolDBEntities();
        }
        public ActionResult test()
        {
            return View();
        }
        public ActionResult StartPage()
        {
            return View();
        }
        // GET: Admin
        public ActionResult Student()
        {
            List<Student> students = new List<Student>();
            foreach (var item in scl.Students)
            {
                students.Add(new Student { RollNo= item.RollNo,Name=item.Name,DOB=item.DOB,ClassNo=item.ClassNo ,Class= item.Class});
            }
            return View(students);
        }

        // GET: Admin/Details/5
        public ActionResult DetailsStudent(int id)
        {
            return View(scl.Students.ToList().Find(temp => temp.RollNo == id));
        }

        // GET: Admin/Create
        public ActionResult CreateStudent()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult CreateStudent(FormCollection collection)
        {
            try
            {
                Student s = new Student();
                s.RollNo =Int32.Parse( Request["RollNo"]);
                s.Name = Request["Name"];
                s.DOB = DateTime.Parse(Request["DOB"]);
                s.ClassNo = Int32.Parse(Request["ClassNo"]);
                scl.Students.Add(s);
                scl.SaveChanges();
                return RedirectToAction("Student");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult EditStudent(int id)
        {
            Student s = scl.Students.ToList().Find(temp => temp.RollNo == id);
            return View(s);
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult EditStudent(int id, FormCollection collection)
        {
            //try
            //{
               Student s = scl.Students.ToList().Find(temp => temp.RollNo == id);
                s.DOB =DateTime.Parse( Request["DOB"]);
                s.Name = Request["Name"];
                s.ClassNo = Int32.Parse(Request["ClassNo"]);
                scl.SaveChanges();
                return RedirectToAction("Student");
           // }
            //catch
            //{
            //    return View();
            //}
        }

        // GET: Admin/Delete/5
        public ActionResult DeleteStudent(int id)
        {
            Student s = scl.Students.ToList().Find(temp => temp.RollNo == id);
            return View(s);
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult DeleteStudent(int id, FormCollection collection)
        {
            try
            {
                Student s = scl.Students.ToList().Find(temp => temp.RollNo == id);
                scl.Students.Remove(s);
                scl.SaveChanges();
                return RedirectToAction("Student");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Class()
        {
            List<Class> classes = new List<Class>();
            classes = scl.Classes.ToList();
            return View(classes);
        }

        public ActionResult ClassCreate()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ClassCreate(FormCollection collection)
        {
            Class c = new Class();
            c.ClassNo = Int32.Parse(Request["ClassNo"]);
            c.RoomNo = Int32.Parse(Request["RoomNo"]);
            c.Strength = Int32.Parse(Request["Strength"]);
            c.ClassTeacher = Request["ClassTeacher"];
            scl.Classes.Add(c);
            scl.SaveChanges();
            return RedirectToAction("Class");
        }
        public ActionResult ClassEdit(int id)
        {
           Class c = scl.Classes.ToList().Find(temp => temp.ClassNo == id);
            return View(c); 
        }
        [HttpPost]
        public ActionResult ClassEdit(int id,FormCollection collection)
        {
            Class c = scl.Classes.ToList().Find(temp => temp.ClassNo == id);
            c.ClassNo = Int32.Parse(Request["ClassNo"]);
            c.RoomNo = Int32.Parse(Request["RoomNo"]);
            c.Strength = Int32.Parse(Request["Strength"]);
            c.ClassTeacher = Request["ClassTeacher"];
            scl.SaveChanges();
            return RedirectToAction("Class");
        }
        public ActionResult ClassDetails(int id)
        {
            Class c = scl.Classes.ToList().Find(temp => temp.ClassNo == id);
            return View(c);
        }
        public ActionResult ClassDelete(int id)
        {
            Class c = scl.Classes.ToList().Find(temp => temp.ClassNo == id);
            return View(c);
        }
        [HttpPost]
        public ActionResult ClassDelete(int id , FormCollection collection)
        {
            Class c = scl.Classes.ToList().Find(temp => temp.ClassNo == id);
            scl.Classes.Remove(c);
            scl.SaveChanges();
            return RedirectToAction("Class");
        }
        public ActionResult Subject()
        {
            List<Subject> subjects = new List<Subject>();
            subjects = scl.Subjects.ToList();
            return View(subjects);
        }
        public ActionResult CreateSubject()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateSubject(FormCollection collection)
        {
            Subject subject = new Subject();
            subject.SubjectId = Int32.Parse(Request["SubjectId"]);
            subject.SubjectName = Request["SubjectName"];
            subject.ClassNo = Int32.Parse(Request["ClassNo"]);
            subject.Duration = Int32.Parse(Request["Duration"]);
            scl.Subjects.Add(subject);  
            scl.SaveChanges();
            return RedirectToAction("Subject");;
        }

        //*****************************************************************************************
        public ActionResult EditSubject(int id)
        {
            Subject c = scl.Subjects.ToList().Find(temp => temp.SubjectId == id);
            return View(c);
        }
        [HttpPost]
        public ActionResult EditSubject(int id, FormCollection collection)
        {
            Subject c = scl.Subjects.ToList().Find(temp => temp.SubjectId == id);
            c.SubjectId =Convert.ToInt32(Request["SubjectId"]);
            c.ClassNo = Int32.Parse(Request["ClassNo"]);
            c.Duration = Int32.Parse(Request["Duration"]);
            c.SubjectName = Request["SubjectName"];
            scl.SaveChanges();
            return RedirectToAction("Subject");
        }
        //***************************************************************************************
        public ActionResult DetailsSubject(int id)
        {
            Subject c = scl.Subjects.ToList().Find(temp => temp.SubjectId == id);
            return View(c);
        }
        public ActionResult Deletesubject(int id)
        {
            Subject c = scl.Subjects.ToList().Find(temp => temp.SubjectId == id);
            return View(c);
        }
        [HttpPost]
        public ActionResult DeleteSubject(int id, FormCollection collection)
        {
            Subject c = scl.Subjects.ToList().Find(temp => temp.SubjectId == id);
            scl.Subjects.Remove(c);
            scl.SaveChanges();
            return RedirectToAction("Subject");
        }

    }

}

School/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace School.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

School/Views/Admin/Class.cshtml
@model IEnumerable<School.Class>

@{
    ViewBag.Title = "Class";
    Layout = "~/Views/Shared/_ClassLayout.cshtml";
}

<h2>Class</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClassNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Strength)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClassTeacher)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ClassNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Strength)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClassTeacher)
        </td>
        <td>
            @Html.ActionLink("Edit", "ClassEdit", new {  id=item.ClassNo }) |
            @Html.ActionLink("Details", "ClassDetails", new { id=item.ClassNo }) |
            @Html.ActionLink("Delete", "ClassDelete", new {  id=item.ClassNo })
        </td>
    </tr>
}

</table>

School/Views/Admin/ClassCreate.cshtml
@model School.Class

@{
    ViewBag.Title = "ClassCreate";
    Layout = "~/Views/Shared/_ClassLayout.cshtml";
}

<h2>ClassCreate</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Class</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClassNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Strength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Strength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Strength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassTeacher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassTeacher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassTeacher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Class")
</div>

School/Views/Admin/ClassDelete.cshtml
@model School.Class

@{
    ViewBag.Title = "ClassDelete";
    Layout = "~/Views/Shared/_ClassLayout.cshtml";
}

<h2>ClassDelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Class</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Strength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Strength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassTeacher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassTeacher)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Class")
        </div>
    }
</div>

School/Views/Admin/ClassDetails.cshtml
@model School.Class

@{
    ViewBag.Title = "ClassDetails";
    Layout = "~/Views/Shared/_ClassLayout.cshtml";
}

<h2>ClassDetails</h2>

<div>
    <h4>Class</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoomNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Strength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Strength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassTeacher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassTeacher)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "ClassEdit", new { id = Model.ClassNo }) |
    @Html.ActionLink("Back to List", "Student")
</p>

School/Views/Admin/ClassEdit.cshtml
@model School.Class

@{
    ViewBag.Title = "ClassEdit";
    Layout = "~/Views/Shared/_ClassLayout.cshtml";
}

<h2>ClassEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Class</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClassNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RoomNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RoomNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Strength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Strength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Strength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassTeacher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassTeacher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassTeacher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Class")
</div>

School/Views/Admin/CreateStudent.cshtml
@model School.Student

@{
    ViewBag.Title = "CreateStudent";
    Layout = "~/Views/Shared/_SchoolLayout.cshtml";
}

<h2>CreateStudent</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RollNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RollNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RollNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassClassNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassClassNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassClassNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

School/Views/Admin/DeleteStudent.cshtml
@model School.Student

@{
    ViewBag.Title = "DeleteStudent";
    Layout = "~/Views/Shared/_SchoolLayout.cshtml";
}

<h2>DeleteStudent</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RollNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RollNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassNo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Student")
        </div>
    }
</div>

School/Views/Admin/StartPage.cshtml
@*@{
        Layout = null;
    }

    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>StartPage</title>
    </head>
    <body>
        <div>
        </div>
    </body>
    </html>*@

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StartPage</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <style>
        .center {
            /*
            display: flex;
            justify-content: center;
            vertical-align:central;
            height:150px;*/
            padding: 70px 0;
            text-align: center;
            width: 800px;
            vertical-align: middle;
            margin: 0 auto;
            /* position: absolute;
            width: 300px;
            height: 200px;
            z-index: 15;
            top: 50%;
            left: 50%;
            margin: -100px 0 0 -150px;*/
        }
    </style>
</head>
<body style=" background-image: url(../../Images/pngtree-school-school-background-picture-image_348548.jpg)">
    <div>
        <div class="center">
            <div class="col-md-4">
                <button class="btn btn-primary btn-lg" type="button" onclick="location.href = '@Url.Action("Student","Admin")'">Student</button>
            </div>
            <div class="col-md-4">
                <button class="btn btn-primary btn-lg " type="button" onclick="location.href = '@Url.Action("Class","Admin")'">Class</button>
            </div>
            <div class="col-md-4">
                <button class="btn btn-primary btn-lg" type="button" onclick="location.href = '@Url.Action("Subject","Admin")'">Subject</button>
            </div>
        </div>
    </div>

</body>
</html>

School/Views/Admin/test.cshtml
@{
    ViewBag.Title = "test";
    Layout = "~/Views/Shared/_SchoolLayout.cshtml";
}

<h2>test</h2>

School/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

School/Views/Home/View.cshtml
@{
    ViewBag.Title = "View";
}

<h2>View</h2>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StartPage</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <style>
        .center {
            /*
            display: flex;
            justify-content: center;
            vertical-align:central;
            height:150px;*/
              padding: 70px 0;
            text-align: center;
            width: 800px;
            vertical-align:middle;
            margin: 0 auto;
          
            /* position: absolute;
            width: 300px;
            height: 200px;
            z-index: 15;
            top: 50%;
            left: 50%;
            margin: -100px 0 0 -150px;*/
           
        }

    </style>
</head>
<body style=" background-image: url(../../Images/pngtree-school-school-background-picture-image_348548.jpg)">
    <div>
        <div class="center">
            <div class="col-md-4">
                <button class="btn btn-primary btn-lg" type="button" onclick="location.href = '@Url.Action("Student","Admin")'">Student</button>
            </div>
            <div class="col-md-4">
                <button class="btn btn-primary btn-lg " type="button">Class</button>
            </div>
            <div class="col-md-4">
                <button class="btn btn-primary btn-lg" type="button">Subject</button>
            </div>
        </div>
      </div>
    
</body>
</html>

School/Views/Shared/_ClassLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My School</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("School", "StartPage", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List", "Class", "Admin")</li>
                    <li>@Html.ActionLink("Add", "ClassCreate", "Admin")</li>
                    @*<li>@Html.ActionLink("Edit", "EditStudent", "Admin")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My School</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

School/Views/Shared/_SchoolLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My School</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("School", "StartPage", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List", "Student", "Admin")</li>
                    <li>@Html.ActionLink("Add", "CreateStudent", "Admin")</li>
                    @*<li>@Html.ActionLink("Edit", "EditStudent", "Admin")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My School</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

School/Views/Shared/_SubjectLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My School</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("School", "StartPage", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List", "Subject", "Admin")</li>
                    <li>@Html.ActionLink("Add", "CreateSubject", "Admin")</li>
                    @*<li>@Html.ActionLink("Edit", "EditStudent", "Admin")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My School</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>